[package]
name = "slang_struct"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "Macro that converts Slang style struct definitions into rust structs"
repository = "https://github.com/FacelessTiger/slang-struct-rs"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.101"
quote = "1.0.41"
syn = "2.0.106"
regex = "1.12.1"
logos = "0.15.1"

[features]
glam = []
bytemuck = []
